spring.application.name=championship

# Circuit Breaker - kafkaProducer
resilience4j.circuitbreaker.instances.kafkaProducer.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaProducer.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaProducer.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafkaProducer.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.kafkaProducer.register-health-indicator=true

# Bulkhead - kafkaProducer
resilience4j.bulkhead.instances.kafkaProducer.max-concurrent-calls=5
resilience4j.bulkhead.instances.kafkaProducer.max-wait-duration=500ms
